### PR TITLE
Add Mane columns to transcripts file downloaded from Ensembl

### LINKED ISSUE #40: Retrieve also MANE transcript ID from Ensembl
With the following URL: http://useast.ensembl.org/biomart/martview/bbf879decaed48b838293b85b847ba8b?VIRTUALSCHEMANAME=default&ATTRIBUTES=hsapiens_gene_ensembl.default.feature_page.ensembl_gene_id|hsapiens_gene_ensembl.default.feature_page.ensembl_transcript_id|hsapiens_gene_ensembl.default.feature_page.transcript_start|hsapiens_gene_ensembl.default.feature_page.transcript_end|hsapiens_gene_ensembl.default.feature_page.chromosome_name|hsapiens_gene_ensembl.default.feature_page.refseq_mrna_predicted|hsapiens_gene_ensembl.default.feature_page.refseq_mrna|hsapiens_gene_ensembl.default.feature_page.refseq_ncrna|hsapiens_gene_ensembl.default.feature_page.transcript_mane_select|hsapiens_gene_ensembl.default.feature_page.transcript_mane_plus_clinical&FILTERS=hsapiens_gene_ensembl.default.filters.transcript_source."ensembl"|hsapiens_gene_ensembl.default.filters.chromosome_name."1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22"&VISIBLEPANEL=resultspanel

This should help fixing this: https://github.com/Clinical-Genomics/chanjo2/issues/19

### PR DESCRIPTION
**Pull request by northwestwitch**
### This PR adds | fixes:
- Fix #40 

### How to test:
- Download transcripts in build 38 and make sure that the Mane Transcripts columns contain data
- Downloading transcripts in build 38 should work as before

### Review:
- [x] Code approved by HS
- [x] Tests executed by CR

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
I'm testing this and while Mane Select transcripts are downloaded fine, the column for the Mane Plus Clinical ones stays empty:

image

**Comment by northwestwitch** [comment]
Ah look, it works! It's just that the Mane Plus Clinical ones are relatively few!

image

**Comment by northwestwitch** [comment]
Ok, but then of course I get error if I try to download the transcripts in build 37:

image

I need to differentiate the query attributes according to the build!

**Comment by northwestwitch** [comment]
Ok fixed: 🆗 

image

**Review by henrikstranneheim — APPROVED** [review]
👍

**Pull request merged**
