### PR TITLE
Use Ensembl v112 to temporarily address the missing exons issue

### PR DESCRIPTION
**Pull request by northwestwitch**
### Fixed
- #74 

### How to test
- Launch the server -> `schug serve --reload`
- In another terminal window, download exons in build 38 -> `curl -X 'GET' 'http://0.0.0.0:8000/exons/ensembl_exons/?build=38' > exons_GRCh38_test.txt`

### Expected test outcome
- Make sure missing exons are present in the downloaded data -> `grep ENST00000414620 exons_GRCh38_test.txt`

## Review
- [x] Tests executed by CR, Jakob37
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is deployed to our stage server now. To test it:

`curl -X 'GET' 'https://schug-stage.scilifelab.se/exons/ensembl_exons/?build=38' > exons_GRCh38_test.txt`

**Comment by Jakob37** [comment]
> @Jakob37 This is deployed to our stage server now. To test it:
> 
> `curl -X 'GET' 'https://schug-stage.scilifelab.se/exons/ensembl_exons/?build=38' > exons_GRCh38_test.txt`

```
$ curl -X 'GET' 'https://schug-stage.scilifelab.se/exons/ensembl_exons/?build=38'
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I'll try it out through my local Schug version ..

**Comment by northwestwitch** [comment]
> $ curl -X 'GET' 'https://schug-stage.scilifelab.se/exons/ensembl_exons/?build=38'
> <html>
> <head><title>403 Forbidden</title></head>
> <body>
> <center><h1>403 Forbidden</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>

Ah sorry!

**Comment by Jakob37** [comment]
Repost from issue - I can see exons now!

```
241127_schug_ensembl$ grep ENST00000414620 *
ensembl_transcripts.tsv:7       ENSG00000075624 ENST00000414620 5529282 5562790
exons_GRCh38_test_new.txt:7       ENSG00000075624 ENST00000414620 ENSE00003542066 5529535 5529663 5529658 5529663                 -1      3
exons_GRCh38_test_new.txt:7       ENSG00000075624 ENST00000414620 ENSE00001784252 5562574 5562790 5562574 5562790                 -1      1
exons_GRCh38_test_new.txt:7       ENSG00000075624 ENST00000414620 ENSE00001775033 5540676 5540771 5540676 5540771                 -1      2
exons_GRCh38_test_new.txt:7       ENSG00000075624 ENST00000414620 ENSE00001688018 5529282 5529400     
```

**Pull request merged**
